In [1]:
import os
import sys
import numpy as np
from matplotlib import pyplot as plt


## data files

In [5]:
input_dir = '/data/lakeshore218'
input_files = [f'{input_dir}/data_2022-07-21.dat', f'{input_dir}/data_2022-07-22.dat']
channels = [1,2,3,4]

## Retrieve datas

In [8]:
# read files
inputdata = None
for i, _filename in enumerate(input_files):
    _file = open(_filename)
    _inputdata = np.loadtxt(_file, delimiter=' ', comments='#', dtype=str)
    _file.close()
    if i == 0: inputdata = _inputdata
    else: inputdata = np.concatenate([inputdata, _inputdata])
    pass
print(f'full data (size = {len(inputdata)})= {inputdata}')

# retrieve data
time = []
temp_data = [[] for c in channels]
raw_data = [[] for c in channels]
for _inputdata in inputdata:
    time.append( int(_inputdata[0]) )
    for i, c in enumerate(channels):
        temp_data[i].append( float(_inputdata[3+c*3+1]) )
        raw_data[i].append(  float(_inputdata[3+c*3+2]) )
        pass
    pass
time = np.array(time)
temp_data = np.array(temp_data)
raw_data = np.array(raw_data)
print(f'time = {time}')
print(f'temp = {temp_data}')
print(f'raw = {raw_data}')

full data (size = 19148)= [['1658377781' '2022/07/21' '13:29:41' ... '8ch' '0.000000' '0.000000']
 ['1658377786' '2022/07/21' '13:29:46' ... '8ch' '0.000000' '0.000000']
 ['1658377790' '2022/07/21' '13:29:50' ... '8ch' '0.000000' '0.000000']
 ...
 ['1658468048' '2022/07/22' '14:34:08' ... '8ch' '0.000000' '0.000000']
 ['1658468052' '2022/07/22' '14:34:12' ... '8ch' '0.000000' '0.000000']
 ['1658468057' '2022/07/22' '14:34:17' ... '8ch' '0.000000' '0.000000']]
time = [1658377781 1658377786 1658377790 ... 1658468048 1658468052 1658468057]
temp = [[297.24 297.24 297.24 ... 219.68 219.72 219.74]
 [297.15 297.15 297.15 ... 219.66 219.69 219.72]
 [296.56 296.56 296.56 ... 219.19 219.23 219.26]
 [  0.     0.     0.   ...   0.     0.     0.  ]]
raw = [[0.566  0.566  0.566  ... 0.7408 0.7407 0.7406]
 [0.5662 0.5662 0.5662 ... 0.7408 0.7407 0.7407]
 [0.5676 0.5676 0.5676 ... 0.7418 0.7418 0.7417]
 [0.     0.     0.     ... 0.     0.     0.    ]]


## Plot all datas

In [ ]:
for c 
plt.plot(time, temp)